package ee.ut.cs.HEALTH.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A type-safe value class for the unique identifier of a routine.
 *
 * Using a value class helps prevent accidental misuse of primitive types like Long,
 * ensuring that only valid routine IDs are used where required.
 *
 * @property value The underlying ID value.
 */
@JvmInline value class RoutineId(val value: Long)

/**
 * Represents a workout routine in the database.
 *
 * This data class defines the structure of the "routines" table. Each instance
 * corresponds to a single row in that table.
 *
 * @property id The unique primary key for the routine, automatically generated by the database.
 * @property name The user-defined name of the routine.
 * @property description An optional, longer description providing details about the routine.
 * @property counter A counter to track how many times this routine has been completed. Defaults to 0.
 */
@Entity(tableName = "routines")
data class RoutineEntity(
    @PrimaryKey(autoGenerate = true)
    val id: RoutineId = RoutineId(0),
    val name: String,
    val description: String?,
    val counter: Int = 0
)
